## Basic Configuration

baseurl = "https://tribolet.fr/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Luc Tribolet"
title = "Luc Tribolet"

theme = "hugo-goa"

## Hugo Built-in Features
# disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
# googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "Luc Tribolet"
intro = "Solutions Architect"
description = "Looking for some adventures in Vancouver, BC. Previously @Splio, @BazarChicFR and @rueducommerce."
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Luc Tribolet, Solutions Architect"
keywords = "luc tribolet, engineer, architect, php, web, developer"

## Social Accounts
[params.social]
github = "ltribolet"
instagram = "luc.tribolet"
linkedin = "luctribolet"
twitter = "luctribolet"
email = "luc.tribolet@gmail.com"

## Extras
[params.extra]
copyright = "© 2019. Luc Tribolet. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = false

## Main Menu
[[menu.main]]
    name = "resume"
    identifier = "resume"
    weight = 200
    url = "/resume/"
